In [16]:
import numpy as np
import itertools
import pandas as pd
import openmeteo_requests
import requests_cache
from retry_requests import retry
from datetime import datetime, timedelta, timezone
from datetime import datetime, timedelta, timezone
import requests

In [5]:
end_date = datetime(2026, 3, 1, tzinfo=timezone.utc)
print(end_date)
start_date = end_date - timedelta(days=365*3)
print(start_date)
start_str = start_date.strftime('%Y-%m-%d')
end_str = end_date.strftime('%Y-%m-%d')

cache_session = requests_cache.CachedSession('.cache', expire_after=-1)
retry_session = retry(cache_session, retries=5, backoff_factor=0.2)
openmeteo = openmeteo_requests.Client(session=retry_session)

2026-03-01 00:00:00+00:00
2023-03-02 00:00:00+00:00

In [8]:

# Your 8x8 grid (64 points)
lats = np.linspace(49.0, 60.0, 11) 
lons = np.linspace(-9.0, 2.0, 11)  
grid_points = list(itertools.product(lats, lons))
api_lats = [p[0] for p in grid_points]
api_lons = [p[1] for p in grid_points]


params = {
    "latitude": api_lats,    
    "longitude": api_lons,   
    "start_date": start_str, 
    "end_date": end_str,
    "hourly": ["temperature_2m", "wind_speed_100m", "cloud_cover", "wind_direction_100m"]
}

responses = openmeteo.weather_api("https://archive-api.open-meteo.com/v1/archive", params=params)

print("Parsing and averaging grid weather data...")
all_grid_data = []

for response in responses:
    hourly = response.Hourly()
    # Create a dataframe for this specific grid coordinate
    df_coord = pd.DataFrame({
        "time": pd.date_range(
            start=pd.to_datetime(hourly.Time(), unit="s", utc=True),
            end=pd.to_datetime(hourly.TimeEnd(), unit="s", utc=True),
            freq=pd.Timedelta(seconds=hourly.Interval()),
            inclusive="left"
        ),
        "temp": hourly.Variables(0).ValuesAsNumpy(),
        "wind_speed": hourly.Variables(1).ValuesAsNumpy(),
        "clouds": hourly.Variables(2).ValuesAsNumpy(),
        "wind_dir": hourly.Variables(3).ValuesAsNumpy()
    })
    all_grid_data.append(df_coord)


weather_df = pd.concat(all_grid_data).groupby("time").mean().reset_index()

# win dir encoding
wind_dir_rad = weather_df['wind_dir'] * np.pi / 180
weather_df['wind_sin'] = np.sin(wind_dir_rad)
weather_df['wind_cos'] = np.cos(wind_dir_rad)

weather_df = weather_df.drop(columns=['wind_dir'])

Parsing and averaging grid weather data...

In [9]:
all_grid_data

[                           time   temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00   9.00   19.130875   100.0   70.201042
 1     2023-03-02 01:00:00+00:00   9.05   20.140705   100.0   65.725571
 2     2023-03-02 02:00:00+00:00   8.50   19.513195    63.0   60.124096
 3     2023-03-02 03:00:00+00:00   8.55   15.683774    48.0   58.134064
 4     2023-03-02 04:00:00+00:00   8.60   15.546833    94.0   47.815628
 ...                         ...    ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  12.10   77.890717   100.0  190.115295
 26300 2026-03-01 20:00:00+00:00  12.15   79.247444   100.0  189.676208
 26301 2026-03-01 21:00:00+00:00  12.20   78.863007   100.0  191.053421
 26302 2026-03-01 22:00:00+00:00  10.95   39.377647   100.0  298.087799
 26303 2026-03-01 23:00:00+00:00  10.30   29.516706   100.0  291.087769

 [26304 rows x 5 columns],
                            time   temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00   8.85   18.681883   100.0   64.916443
 1     2023-03-02 01:00:00+00:00   9.00   16.311613    66.0   67.963715
 2     2023-03-02 02:00:00+00:00   9.05   12.522619    99.0   71.564964
 3     2023-03-02 03:00:00+00:00   9.00   10.495713    97.0   59.036320
 4     2023-03-02 04:00:00+00:00   9.15    9.957108    48.0   49.398785
 ...                         ...    ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  11.95   75.120407   100.0  188.265930
 26300 2026-03-01 20:00:00+00:00  12.00   74.034065   100.0  187.263153
 26301 2026-03-01 21:00:00+00:00  12.15   74.125259   100.0  186.693481
 26302 2026-03-01 22:00:00+00:00  12.15   73.950218   100.0  187.834167
 26303 2026-03-01 23:00:00+00:00  12.15   72.192795   100.0  188.170425

 [26304 rows x 5 columns],
                            time   temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00   8.95   24.661970    99.0   56.309898
 1     2023-03-02 01:00:00+00:00   7.90   22.907431    58.0   59.808472
 2     2023-03-02 02:00:00+00:00   7.50   19.161337    87.0   64.397865
 3     2023-03-02 03:00:00+00:00   8.00   15.990646    97.0   58.815090
 4     2023-03-02 04:00:00+00:00   8.00   17.727943    66.0   60.832493
 ...                         ...    ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  11.85   71.232025   100.0  185.364746
 26300 2026-03-01 20:00:00+00:00  11.85   71.183571   100.0  184.931992
 26301 2026-03-01 21:00:00+00:00  11.85   71.125290   100.0  184.354141
 26302 2026-03-01 22:00:00+00:00  11.90   70.380692   100.0  184.106415
 26303 2026-03-01 23:00:00+00:00  11.90   69.513557   100.0  181.780609

 [26304 rows x 5 columns],
                            time   temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00   8.05   26.661880    52.0   55.451576
 1     2023-03-02 01:00:00+00:00   7.90   21.611996    75.0   60.018444
 2     2023-03-02 02:00:00+00:00   7.85   16.595179    81.0   65.658920
 3     2023-03-02 03:00:00+00:00   7.50   17.227421   100.0   63.970474
 4     2023-03-02 04:00:00+00:00   7.95   17.076298   100.0   71.564964
 ...                         ...    ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  11.70   64.250671   100.0  184.177032
 26300 2026-03-01 20:00:00+00:00  11.80   63.686684   100.0  183.889404
 26301 2026-03-01 21:00:00+00:00  11.90   67.043655   100.0  185.082916
 26302 2026-03-01 22:00:00+00:00  11.85   65.429436   100.0  182.996155
 26303 2026-03-01 23:00:00+00:00  11.90   63.622551   100.0  182.919006

 [26304 rows x 5 columns],
                            time   temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00   8.45   25.842384   100.0   71.312561
 1     2023-03-02 01:00:00+00:00   8.50   22.657131    87.0   72.428650
 2     2023-03-02 02:00:00+00:00   8.30   20.833395   100.0   71.878052
 3     2023-03-02 03:00:00+00:00   8.40   18.331741   100.0   70.497467
 4     2023-03-02 04:00:00+00:00   8.45   17.584810   100.0   67.109421
 ...                         ...    ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  11.45   57.963352   100.0  186.418686
 26300 2026-03-01 20:00:00+00:00  11.40   57.356766   100.0  187.392548
 26301 2026-03-01 21:00:00+00:00  11.30   51.560493   100.0  183.201950
 26302 2026-03-01 22:00:00+00:00  11.45   52.855366   100.0  186.059982
 26303 2026-03-01 23:00:00+00:00  11.55   55.123802   100.0  186.939270

 [26304 rows x 5 columns],
                            time   temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00   8.40   25.862436    90.0   73.835434
 1     2023-03-02 01:00:00+00:00   8.35   23.491207   100.0   74.898849
 2     2023-03-02 02:00:00+00:00   8.35   22.702845   100.0   62.622387
 3     2023-03-02 03:00:00+00:00   8.30   23.113008   100.0   52.594578
 4     2023-03-02 04:00:00+00:00   8.25   24.014996   100.0   49.864578
 ...                         ...    ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  11.30   45.779839   100.0  182.929840
 26300 2026-03-01 20:00:00+00:00  11.00   43.802547   100.0  183.062225
 26301 2026-03-01 21:00:00+00:00  10.90   44.362244   100.0  183.489258
 26302 2026-03-01 22:00:00+00:00  10.85   42.144608   100.0  181.958023
 26303 2026-03-01 23:00:00+00:00  10.80   41.221569    66.0  179.499619

 [26304 rows x 5 columns],
                            time   temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00   7.35   28.673721    80.0   61.504463
 1     2023-03-02 01:00:00+00:00   7.00   27.169865    91.0   57.994659
 2     2023-03-02 02:00:00+00:00   6.70   26.874910    72.0   50.980602
 3     2023-03-02 03:00:00+00:00   6.50   26.758923    48.0   47.726372
 4     2023-03-02 04:00:00+00:00   6.40   28.528723    72.0   47.045418
 ...                         ...    ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  10.80   49.547104    98.0  177.501465
 26300 2026-03-01 20:00:00+00:00  10.45   49.218727   100.0  174.122696
 26301 2026-03-01 21:00:00+00:00  10.20   49.464638   100.0  175.617371
 26302 2026-03-01 22:00:00+00:00  10.10   48.146214    98.0  176.570709
 26303 2026-03-01 23:00:00+00:00  10.00   48.820168    98.0  177.675674

 [26304 rows x 5 columns],
                            time  temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00  0.15   21.599998     0.0   53.130020
 1     2023-03-02 01:00:00+00:00 -0.35   22.322903     0.0   52.205994
 2     2023-03-02 02:00:00+00:00 -0.65   21.533897     0.0   51.788940
 3     2023-03-02 03:00:00+00:00 -0.85   19.174856     0.0   50.332199
 4     2023-03-02 04:00:00+00:00 -0.85   18.668005    16.0   50.477409
 ...                         ...   ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  9.55   38.641350   100.0  184.541916
 26300 2026-03-01 20:00:00+00:00  9.00   39.794655   100.0  178.444870
 26301 2026-03-01 21:00:00+00:00  8.80   42.843407    98.0  174.696701
 26302 2026-03-01 22:00:00+00:00  8.80   45.411400    99.0  177.273743
 26303 2026-03-01 23:00:00+00:00  8.50   45.271698    78.0  176.352692

 [26304 rows x 5 columns],
                            time  temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00 -2.60   17.873556     0.0   34.330269
 1     2023-03-02 01:00:00+00:00 -3.00   16.873980     0.0   33.690102
 2     2023-03-02 02:00:00+00:00 -2.20   14.113652     0.0   37.746864
 3     2023-03-02 03:00:00+00:00 -1.95   12.768586     0.0   40.425995
 4     2023-03-02 04:00:00+00:00 -1.20   11.090103     0.0   35.753979
 ...                         ...   ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  9.50   28.802811    93.0  173.541275
 26300 2026-03-01 20:00:00+00:00  8.85   29.463968    63.0  174.742279
 26301 2026-03-01 21:00:00+00:00  8.75   33.424305    90.0  175.057083
 26302 2026-03-01 22:00:00+00:00  8.85   36.064739    99.0  176.566437
 26303 2026-03-01 23:00:00+00:00  8.65   36.806370    99.0  176.074173

 [26304 rows x 5 columns],
                            time  temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00 -1.65   23.358423     0.0   28.539894
 1     2023-03-02 01:00:00+00:00 -2.05   21.897945     0.0   27.407490
 2     2023-03-02 02:00:00+00:00 -2.30   21.273533     0.0   23.962492
 3     2023-03-02 03:00:00+00:00 -2.55   20.188908     0.0   21.991192
 4     2023-03-02 04:00:00+00:00 -2.90   19.191748     0.0   23.198618
 ...                         ...   ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  9.70   22.680000    13.0  180.000000
 26300 2026-03-01 20:00:00+00:00  8.15   26.052162    27.0  168.845383
 26301 2026-03-01 21:00:00+00:00  7.85   30.735231     7.0  174.623383
 26302 2026-03-01 22:00:00+00:00  7.65   32.222008    27.0  173.907318
 26303 2026-03-01 23:00:00+00:00  7.40   31.926540     3.0  172.875076

 [26304 rows x 5 columns],
                            time    temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00 -0.6605   25.992401     0.0   36.552567
 1     2023-03-02 01:00:00+00:00 -1.0105   25.068514     0.0   35.059513
 2     2023-03-02 02:00:00+00:00 -1.4105   24.162947     0.0   33.453342
 3     2023-03-02 03:00:00+00:00 -1.8105   23.847115     0.0   28.886486
 4     2023-03-02 04:00:00+00:00 -2.1605   23.188583     0.0   27.758451
 ...                         ...     ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  8.0895   21.136784    16.0  184.885117
 26300 2026-03-01 20:00:00+00:00  7.5895   22.065973     2.0  185.617493
 26301 2026-03-01 21:00:00+00:00  6.9895   21.626984     0.0  177.137650
 26302 2026-03-01 22:00:00+00:00  6.3395   21.741287     7.0  165.618576
 26303 2026-03-01 23:00:00+00:00  5.9895   22.796841    10.0  164.427399

 [26304 rows x 5 columns],
                            time   temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00   8.85   21.300930   100.0   59.534538
 1     2023-03-02 01:00:00+00:00   8.90   18.250259    96.0   67.988670
 2     2023-03-02 02:00:00+00:00   8.95   21.096123    85.0   64.746872
 3     2023-03-02 03:00:00+00:00   7.60   25.356371    98.0   51.340172
 4     2023-03-02 04:00:00+00:00   8.05   20.746122    79.0   51.340172
 ...                         ...    ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  11.80   80.729340   100.0  188.979187
 26300 2026-03-01 20:00:00+00:00  11.65   76.713371   100.0  193.155853
 26301 2026-03-01 21:00:00+00:00  10.90   40.728157   100.0  272.786469
 26302 2026-03-01 22:00:00+00:00  10.45   36.885948   100.0  277.853210
 26303 2026-03-01 23:00:00+00:00  10.45   28.619999   100.0  270.000000

 [26304 rows x 5 columns],
                            time   temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00   9.10   23.166218    97.0   57.050781
 1     2023-03-02 01:00:00+00:00   7.60   26.562046    93.0   57.171459
 2     2023-03-02 02:00:00+00:00   7.85   21.485697    84.0   58.707020
 3     2023-03-02 03:00:00+00:00   7.90   20.991426    99.0   67.833611
 4     2023-03-02 04:00:00+00:00   7.80   21.129885    98.0   66.929565
 ...                         ...    ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  11.55   78.946159   100.0  187.335571
 26300 2026-03-01 20:00:00+00:00  11.65   79.349792   100.0  187.560196
 26301 2026-03-01 21:00:00+00:00  11.65   77.258591   100.0  188.035614
 26302 2026-03-01 22:00:00+00:00  11.75   79.816353   100.0  187.124924
 26303 2026-03-01 23:00:00+00:00  11.45   55.351681   100.0  218.397949

 [26304 rows x 5 columns],
                            time   temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00   8.25   27.859905    97.0   64.759514
 1     2023-03-02 01:00:00+00:00   7.90   25.600533    95.0   64.155670
 2     2023-03-02 02:00:00+00:00   7.60   24.881702    97.0   58.609787
 3     2023-03-02 03:00:00+00:00   7.95   21.986542    93.0   50.314590
 4     2023-03-02 04:00:00+00:00   7.90   25.318008    80.0   60.154160
 ...                         ...    ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  11.45   75.439758   100.0  185.751312
 26300 2026-03-01 20:00:00+00:00  11.50   76.409943   100.0  186.220856
 26301 2026-03-01 21:00:00+00:00  11.45   76.088066   100.0  185.157532
 26302 2026-03-01 22:00:00+00:00  11.55   76.486229   100.0  183.778122
 26303 2026-03-01 23:00:00+00:00  11.55   75.146278   100.0  182.745834

 [26304 rows x 5 columns],
                            time   temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00   6.80   26.368616    78.0   51.095856
 1     2023-03-02 01:00:00+00:00   6.40   23.000591    49.0   50.079674
 2     2023-03-02 02:00:00+00:00   5.80   24.387178    49.0   58.891258
 3     2023-03-02 03:00:00+00:00   5.25   23.068108    24.0   67.036194
 4     2023-03-02 04:00:00+00:00   5.00   21.862406    36.0   72.758453
 ...                         ...    ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  11.05   68.365173   100.0  185.590408
 26300 2026-03-01 20:00:00+00:00  11.05   70.368027   100.0  183.960236
 26301 2026-03-01 21:00:00+00:00  11.05   70.112488   100.0  182.943146
 26302 2026-03-01 22:00:00+00:00  11.20   68.504372   100.0  183.163055
 26303 2026-03-01 23:00:00+00:00  11.25   67.547020   100.0  182.138000

 [26304 rows x 5 columns],
                            time   temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00   7.80   29.301876   100.0   47.489597
 1     2023-03-02 01:00:00+00:00   7.40   29.460672    49.0   57.475128
 2     2023-03-02 02:00:00+00:00   7.30   29.162222    93.0   61.220299
 3     2023-03-02 03:00:00+00:00   7.15   27.238941    51.0   60.724850
 4     2023-03-02 04:00:00+00:00   7.05   26.407907   100.0   62.387074
 ...                         ...    ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  11.15   63.681602   100.0  189.435623
 26300 2026-03-01 20:00:00+00:00  11.15   65.219147   100.0  187.772202
 26301 2026-03-01 21:00:00+00:00  11.10   61.198414   100.0  187.605682
 26302 2026-03-01 22:00:00+00:00  11.15   62.759109    99.0  187.084152
 26303 2026-03-01 23:00:00+00:00  11.05   58.328049   100.0  184.602036

 [26304 rows x 5 columns],
                            time   temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00   7.85   28.364710   100.0   66.037506
 1     2023-03-02 01:00:00+00:00   7.85   25.872454   100.0   68.790703
 2     2023-03-02 02:00:00+00:00   7.55   26.576681    69.0   65.170677
 3     2023-03-02 03:00:00+00:00   7.85   26.121714    73.0   60.255219
 4     2023-03-02 04:00:00+00:00   7.70   27.852928   100.0   63.103848
 ...                         ...    ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  11.60   53.805244   100.0  190.407654
 26300 2026-03-01 20:00:00+00:00  11.50   55.220112   100.0  189.001678
 26301 2026-03-01 21:00:00+00:00  11.30   55.342899   100.0  188.604401
 26302 2026-03-01 22:00:00+00:00  11.15   53.773022   100.0  184.030884
 26303 2026-03-01 23:00:00+00:00  11.05   50.941269   100.0  180.404907

 [26304 rows x 5 columns],
                            time   temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00   7.80   30.631746   100.0   66.447731
 1     2023-03-02 01:00:00+00:00   7.55   28.337282   100.0   62.783974
 2     2023-03-02 02:00:00+00:00   7.25   27.362368    93.0   57.355381
 3     2023-03-02 03:00:00+00:00   6.90   27.887802   100.0   50.762650
 4     2023-03-02 04:00:00+00:00   6.50   29.301876    97.0   47.489597
 ...                         ...    ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  11.45   55.685204   100.0  185.378784
 26300 2026-03-01 20:00:00+00:00  11.25   54.862511   100.0  186.215546
 26301 2026-03-01 21:00:00+00:00  11.10   53.176823   100.0  185.633301
 26302 2026-03-01 22:00:00+00:00  10.85   50.003078   100.0  184.335342
 26303 2026-03-01 23:00:00+00:00  10.75   49.478718   100.0  184.590454

 [26304 rows x 5 columns],
                            time   temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00   7.20   30.007679    35.0   59.743652
 1     2023-03-02 01:00:00+00:00   6.95   30.968370    86.0   54.462238
 2     2023-03-02 02:00:00+00:00   6.75   29.871325    59.0   49.398785
 3     2023-03-02 03:00:00+00:00   6.65   29.059830    90.0   48.012871
 4     2023-03-02 04:00:00+00:00   6.55   30.319178    99.0   47.406010
 ...                         ...    ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  11.25   46.911327   100.0  186.388657
 26300 2026-03-01 20:00:00+00:00  11.10   47.374207    95.0  182.177444
 26301 2026-03-01 21:00:00+00:00  10.90   47.381386   100.0  182.394958
 26302 2026-03-01 22:00:00+00:00  10.60   44.101467   100.0  180.467697
 26303 2026-03-01 23:00:00+00:00  10.40   40.874271    77.0  181.514038

 [26304 rows x 5 columns],
                            time   temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00   6.60   31.673861     8.0   58.477882
 1     2023-03-02 01:00:00+00:00   6.70   30.760519     0.0   55.007900
 2     2023-03-02 02:00:00+00:00   6.75   29.964457     0.0   54.782326
 3     2023-03-02 03:00:00+00:00   6.65   30.760519     0.0   55.007900
 4     2023-03-02 04:00:00+00:00   6.60   31.262014     0.0   54.845753
 ...                         ...    ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  11.00   48.058651    93.0  184.941772
 26300 2026-03-01 20:00:00+00:00  10.90   49.003986    98.0  185.480148
 26301 2026-03-01 21:00:00+00:00  10.70   44.856129    99.0  182.299744
 26302 2026-03-01 22:00:00+00:00  10.55   44.101467    99.0  179.532303
 26303 2026-03-01 23:00:00+00:00  10.40   44.483315   100.0  178.144958

 [26304 rows x 5 columns],
                            time   temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00   5.45   30.096085     0.0   53.267090
 1     2023-03-02 01:00:00+00:00   5.10   29.017429     0.0   52.561356
 2     2023-03-02 02:00:00+00:00   4.70   26.867676     0.0   54.819221
 3     2023-03-02 03:00:00+00:00   4.35   25.161400     0.0   56.082535
 4     2023-03-02 04:00:00+00:00   4.25   23.051247     0.0   51.340172
 ...                         ...    ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  10.70   38.565815     8.0  188.319107
 26300 2026-03-01 20:00:00+00:00  10.55   38.761486    17.0  186.398865
 26301 2026-03-01 21:00:00+00:00  10.40   37.132828     0.0  183.056519
 26302 2026-03-01 22:00:00+00:00  10.10   35.217953     8.0  175.309402
 26303 2026-03-01 23:00:00+00:00   9.75   34.831276    33.0  175.851181

 [26304 rows x 5 columns],
                            time  temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00 -0.25   28.449112     0.0   51.679852
 1     2023-03-02 01:00:00+00:00 -0.45   28.673721     0.0   51.115498
 2     2023-03-02 02:00:00+00:00 -0.90   28.075384     0.0   49.159740
 3     2023-03-02 03:00:00+00:00 -1.25   28.284639     0.0   42.420803
 4     2023-03-02 04:00:00+00:00 -1.60   27.567635     0.0   40.763515
 ...                         ...   ...         ...     ...         ...
 26299 2026-03-01 19:00:00+00:00  9.55   27.725258    12.0  181.115982
 26300 2026-03-01 20:00:00+00:00  8.35   30.424791    58.0  181.016953
 26301 2026-03-01 21:00:00+00:00  7.75   28.985029     7.0  181.067474
 26302 2026-03-01 22:00:00+00:00  7.00   26.563267     8.0  174.946259
 26303 2026-03-01 23:00:00+00:00  6.55   29.118856     5.0  166.049637

 [26304 rows x 5 columns],
                            time   temp  wind_speed  clouds    wind_dir
 0     2023-03-02 00:00:00+00:00   7.65   34.247337   100.0   56.142860
 1     2023-03-02 01:00:00+00:00   7.85   33.283943   100.0   51.146618
 2     2023-03-02 02:00:00+00:00   7.45   32.839027   100.0   44.555908
 3     2023-03-02 03:00:00+00:00   7.20   33.394730   100.0   41.941231

In [10]:
all_locations_data = []

for i, response in enumerate(responses):
    lat = round(api_lats[i])
    lon = round(api_lons[i])
    lon_str = str(lon).replace('-', 'm') # minus = m
    lat_str = str(lat).replace('-', 'm')
    
    loc_suffix = f"lat{lat_str}_lon_{lon_str}"

    hourly = response.Hourly()
    
    time = pd.date_range(
        start=pd.to_datetime(hourly.Time(), unit="s", utc=True),
        end=pd.to_datetime(hourly.TimeEnd(), unit="s", utc=True),
        freq=pd.Timedelta(seconds=hourly.Interval()),
        inclusive="left"
    )
    raw_wind_dir_deg = hourly.Variables(3).ValuesAsNumpy()
    
    #  degrees to radians 
    wind_dir_rad = raw_wind_dir_deg * (np.pi / 180)
    data = {
        "time": time,
        f"temp_{loc_suffix}": hourly.Variables(0).ValuesAsNumpy(),
        f"wind_{loc_suffix}": hourly.Variables(1).ValuesAsNumpy(),
        f"clouds_{loc_suffix}": hourly.Variables(2).ValuesAsNumpy(),

        f"wind_sin_{loc_suffix}": np.sin(wind_dir_rad),
        f"wind_cos_{loc_suffix}": np.cos(wind_dir_rad)
    }
    
    all_locations_data.append(pd.DataFrame(data).set_index("time"))

final_df = pd.concat(all_locations_data, axis=1)
final_df = final_df.reset_index(names="time") 

print(f"Shape {final_df.shape}")

Shape (26304, 606)

In [11]:
final_df.columns

Index(['time', 'temp_lat49_lon_m9', 'wind_lat49_lon_m9', 'clouds_lat49_lon_m9',
       'wind_sin_lat49_lon_m9', 'wind_cos_lat49_lon_m9', 'temp_lat49_lon_m8',
       'wind_lat49_lon_m8', 'clouds_lat49_lon_m8', 'wind_sin_lat49_lon_m8',
       ...
       'temp_lat60_lon_1', 'wind_lat60_lon_1', 'clouds_lat60_lon_1',
       'wind_sin_lat60_lon_1', 'wind_cos_lat60_lon_1', 'temp_lat60_lon_2',
       'wind_lat60_lon_2', 'clouds_lat60_lon_2', 'wind_sin_lat60_lon_2',
       'wind_cos_lat60_lon_2'],
      dtype='object', length=606)

In [65]:
final_df.to_csv('grid_weather_11x11_2023-2026.csv', index=False)

In [12]:


def get_elexon_dataset(dataset_name, start_time, end_time):
    """Fetches a specific time window from Elexon."""
    url = f"https://data.elexon.co.uk/bmrs/api/v1/datasets/{dataset_name}"
    params = {"from": start_time, "to": end_time, "format": "json"}
    
    response = requests.get(url, params=params)
    if response.status_code == 200:
        data = response.json()
        if 'data' in data and data['data']:
            return pd.DataFrame(data['data'])
    else:
        print(f"Error {response.status_code}: {response.text}")
    return pd.DataFrame() # Return empty DF on failure

def fetch_month_of_data(dataset_name,start_date,end_date):
    """Loops through the last 30 days in 7-day chunks."""
 
    
    current_start = start_date
    all_chunks = []
    
    
    while current_start < end_date:

        current_end = min(current_start + timedelta(days=7), end_date)
        
        # F Elexon's requirement: YYYY-MM-DDTHH:MMZ
        start_str = current_start.strftime('%Y-%m-%dT%H:%MZ')
        end_str = current_end.strftime('%Y-%m-%dT%H:%MZ')
        
        print(f"Fetching chunk: {start_str} to {end_str}")
        chunk_df = get_elexon_dataset(dataset_name, start_str, end_str)
        print(chunk_df)
        if not chunk_df.empty:
            all_chunks.append(chunk_df)
            
        current_start = current_end
        
    # Combine all the weekly chunks into one DataFrame
    if all_chunks:
        master_df = pd.concat(all_chunks, ignore_index=True)
        
        # Cort chronologically
        if 'startTime' in master_df.columns:
            master_df['startTime'] = pd.to_datetime(master_df['startTime'])
            master_df = master_df.sort_values('startTime').reset_index(drop=True)
            
        return master_df
    else:
        print("No data was fetched.")

In [ ]:
#  1 month of Market Index Data (MID)
monthly_mid_df = fetch_month_of_data("MID", start_date, end_date)
monthly_mid_df=monthly_mid_df.loc[monthly_mid_df['dataProvider']=='APXMIDP']

In [14]:
def fetch_availability_month(start_date, end_date):
    """Fetches FOU2T14D using the correct publishDateTime parameters."""
    current_start = start_date
    all_chunks = []
    
    
    while current_start < end_date:
        current_end = min(current_start + timedelta(days=7), end_date)
        
        start_str = current_start.strftime('%Y-%m-%dT%H:%MZ')
        end_str = current_end.strftime('%Y-%m-%dT%H:%MZ')
        
        print(f"Fetching chunk: {start_str} to {end_str}")
        
        url = "https://data.elexon.co.uk/bmrs/api/v1/datasets/FOU2T14D"
        params = {
            "publishDateTimeFrom": start_str,
            "publishDateTimeTo": end_str,
            "format": "json"
        }
        
        response = requests.get(url, params=params)
        if response.status_code == 200:
            data = response.json()
            if 'data' in data and data['data']:
                all_chunks.append(pd.DataFrame(data['data']))
        else:
            print(f"Error {response.status_code}: {response.text}")
            
        current_start = current_end
        
    if all_chunks:
        return pd.concat(all_chunks, ignore_index=True)
    return pd.DataFrame()

In [17]:

avail_raw = fetch_availability_month(start_date, end_date)

Fetching chunk: 2023-03-02T00:00Z to 2023-03-09T00:00Z
Fetching chunk: 2023-03-09T00:00Z to 2023-03-16T00:00Z
Fetching chunk: 2023-03-16T00:00Z to 2023-03-23T00:00Z
Fetching chunk: 2023-03-23T00:00Z to 2023-03-30T00:00Z
Fetching chunk: 2023-03-30T00:00Z to 2023-04-06T00:00Z
Fetching chunk: 2023-04-06T00:00Z to 2023-04-13T00:00Z
Fetching chunk: 2023-04-13T00:00Z to 2023-04-20T00:00Z
Fetching chunk: 2023-04-20T00:00Z to 2023-04-27T00:00Z
Fetching chunk: 2023-04-27T00:00Z to 2023-05-04T00:00Z
Fetching chunk: 2023-05-04T00:00Z to 2023-05-11T00:00Z
Fetching chunk: 2023-05-11T00:00Z to 2023-05-18T00:00Z
Fetching chunk: 2023-05-18T00:00Z to 2023-05-25T00:00Z
Fetching chunk: 2023-05-25T00:00Z to 2023-06-01T00:00Z
Fetching chunk: 2023-06-01T00:00Z to 2023-06-08T00:00Z
Fetching chunk: 2023-06-08T00:00Z to 2023-06-15T00:00Z
Fetching chunk: 2023-06-15T00:00Z to 2023-06-22T00:00Z
Fetching chunk: 2023-06-22T00:00Z to 2023-06-29T00:00Z
Fetching chunk: 2023-06-29T00:00Z to 2023-07-06T00:00Z
Fetching chunk: 2023-07-06T00:00Z to 2023-07-13T00:00Z
Fetching chunk: 2023-07-13T00:00Z to 2023-07-20T00:00Z
Fetching chunk: 2023-07-20T00:00Z to 2023-07-27T00:00Z
Fetching chunk: 2023-07-27T00:00Z to 2023-08-03T00:00Z
Fetching chunk: 2023-08-03T00:00Z to 2023-08-10T00:00Z
Fetching chunk: 2023-08-10T00:00Z to 2023-08-17T00:00Z
Fetching chunk: 2023-08-17T00:00Z to 2023-08-24T00:00Z
Fetching chunk: 2023-08-24T00:00Z to 2023-08-31T00:00Z
Fetching chunk: 2023-08-31T00:00Z to 2023-09-07T00:00Z
Fetching chunk: 2023-09-07T00:00Z to 2023-09-14T00:00Z
Fetching chunk: 2023-09-14T00:00Z to 2023-09-21T00:00Z
Fetching chunk: 2023-09-21T00:00Z to 2023-09-28T00:00Z
Fetching chunk: 2023-09-28T00:00Z to 2023-10-05T00:00Z
Fetching chunk: 2023-10-05T00:00Z to 2023-10-12T00:00Z
Fetching chunk: 2023-10-12T00:00Z to 2023-10-19T00:00Z
Fetching chunk: 2023-10-19T00:00Z to 2023-10-26T00:00Z
Fetching chunk: 2023-10-26T00:00Z to 2023-11-02T00:00Z
Fetching chunk: 2023-11-02T00:00Z to 2023-11-09T00:00Z
Fetching chunk: 2023-11-09T00:00Z to 2023-11-16T00:00Z
Fetching chunk: 2023-11-16T00:00Z to 2023-11-23T00:00Z
Fetching chunk: 2023-11-23T00:00Z to 2023-11-30T00:00Z
Fetching chunk: 2023-11-30T00:00Z to 2023-12-07T00:00Z
Fetching chunk: 2023-12-07T00:00Z to 2023-12-14T00:00Z
Fetching chunk: 2023-12-14T00:00Z to 2023-12-21T00:00Z
Fetching chunk: 2023-12-21T00:00Z to 2023-12-28T00:00Z
Fetching chunk: 2023-12-28T00:00Z to 2024-01-04T00:00Z
Fetching chunk: 2024-01-04T00:00Z to 2024-01-11T00:00Z
Fetching chunk: 2024-01-11T00:00Z to 2024-01-18T00:00Z
Fetching chunk: 2024-01-18T00:00Z to 2024-01-25T00:00Z
Fetching chunk: 2024-01-25T00:00Z to 2024-02-01T00:00Z
Fetching chunk: 2024-02-01T00:00Z to 2024-02-08T00:00Z
Fetching chunk: 2024-02-08T00:00Z to 2024-02-15T00:00Z
Fetching chunk: 2024-02-15T00:00Z to 2024-02-22T00:00Z
Fetching chunk: 2024-02-22T00:00Z to 2024-02-29T00:00Z
Fetching chunk: 2024-02-29T00:00Z to 2024-03-07T00:00Z
Fetching chunk: 2024-03-07T00:00Z to 2024-03-14T00:00Z
Fetching chunk: 2024-03-14T00:00Z to 2024-03-21T00:00Z
Fetching chunk: 2024-03-21T00:00Z to 2024-03-28T00:00Z
Fetching chunk: 2024-03-28T00:00Z to 2024-04-04T00:00Z
Fetching chunk: 2024-04-04T00:00Z to 2024-04-11T00:00Z
Fetching chunk: 2024-04-11T00:00Z to 2024-04-18T00:00Z
Fetching chunk: 2024-04-18T00:00Z to 2024-04-25T00:00Z
Fetching chunk: 2024-04-25T00:00Z to 2024-05-02T00:00Z
Fetching chunk: 2024-05-02T00:00Z to 2024-05-09T00:00Z
Fetching chunk: 2024-05-09T00:00Z to 2024-05-16T00:00Z
Fetching chunk: 2024-05-16T00:00Z to 2024-05-23T00:00Z
Fetching chunk: 2024-05-23T00:00Z to 2024-05-30T00:00Z
Fetching chunk: 2024-05-30T00:00Z to 2024-06-06T00:00Z
Fetching chunk: 2024-06-06T00:00Z to 2024-06-13T00:00Z
Fetching chunk: 2024-06-13T00:00Z to 2024-06-20T00:00Z
Fetching chunk: 2024-06-20T00:00Z to 2024-06-27T00:00Z
Fetching chunk: 2024-06-27T00:00Z to 2024-07-04T00:00Z
Fetching chunk: 2024-07-04T00:00Z to 2024-07-11T00:00Z
Fetching chunk: 2024-07-11T00:00Z to 2024-07-18T00:00Z
Fetching chunk: 2024-07-18T00:00Z to 2024-07-25T00:00Z
Fetching chunk: 2024-07-25T00:00Z to 2024-08-01T00:00Z
Fetching chunk: 2024-08-01T00:00Z to 2024-08-08T00:00Z
Fetching chunk: 2024-08-08T00:00Z to 2024-08-15T00:00Z
Fetching chunk: 2024-08-15T00:00Z to 2024-08-22T00:00Z
Fetching chunk: 2024-08-22T00:00Z to 2024-08-29T00:00Z
Fetching chunk: 2024-08-29T00:00Z to 2024-09-05T00:00Z
Fetching chunk: 2024-09-05T00:00Z to 2024-09-12T00:00Z
Fetching chunk: 2024-09-12T00:00Z to 2024-09-19T00:00Z
Fetching chunk: 2024-09-19T00:00Z to 2024-09-26T00:00Z
Fetching chunk: 2024-09-26T00:00Z to 2024-10-03T00:00Z
Fetching chunk: 2024-10-03T00:00Z to 2024-10-10T00:00Z
Fetching chunk: 2024-10-10T00:00Z to 2024-10-17T00:00Z
Fetching chunk: 2024-10-17T00:00Z to 2024-10-24T00:00Z
Fetching chunk: 2024-10-24T00:00Z to 2024-10-31T00:00Z
Fetching chunk: 2024-10-31T00:00Z to 2024-11-07T00:00Z
Fetching chunk: 2024-11-07T00:00Z to 2024-11-14T00:00Z
Fetching chunk: 2024-11-14T00:00Z to 2024-11-21T00:00Z
Fetching chunk: 2024-11-21T00:00Z to 2024-11-28T00:00Z
Fetching chunk: 2024-11-28T00:00Z to 2024-12-05T00:00Z
Fetching chunk: 2024-12-05T00:00Z to 2024-12-12T00:00Z
Fetching chunk: 2024-12-12T00:00Z to 2024-12-19T00:00Z
Fetching chunk: 2024-12-19T00:00Z to 2024-12-26T00:00Z
Fetching chunk: 2024-12-26T00:00Z to 2025-01-02T00:00Z
Fetching chunk: 2025-01-02T00:00Z to 2025-01-09T00:00Z
Fetching chunk: 2025-01-09T00:00Z to 2025-01-16T00:00Z
Fetching chunk: 2025-01-16T00:00Z to 2025-01-23T00:00Z
Fetching chunk: 2025-01-23T00:00Z to 2025-01-30T00:00Z
Fetching chunk: 2025-01-30T00:00Z to 2025-02-06T00:00Z
Fetching chunk: 2025-02-06T00:00Z to 2025-02-13T00:00Z
Fetching chunk: 2025-02-13T00:00Z to 2025-02-20T00:00Z
Fetching chunk: 2025-02-20T00:00Z to 2025-02-27T00:00Z
Fetching chunk: 2025-02-27T00:00Z to 2025-03-06T00:00Z
Fetching chunk: 2025-03-06T00:00Z to 2025-03-13T00:00Z
Fetching chunk: 2025-03-13T00:00Z to 2025-03-20T00:00Z
Fetching chunk: 2025-03-20T00:00Z to 2025-03-27T00:00Z
Fetching chunk: 2025-03-27T00:00Z to 2025-04-03T00:00Z
Fetching chunk: 2025-04-03T00:00Z to 2025-04-10T00:00Z
Fetching chunk: 2025-04-10T00:00Z to 2025-04-17T00:00Z
Fetching chunk: 2025-04-17T00:00Z to 2025-04-24T00:00Z
Fetching chunk: 2025-04-24T00:00Z to 2025-05-01T00:00Z
Fetching chunk: 2025-05-01T00:00Z to 2025-05-08T00:00Z
Fetching chunk: 2025-05-08T00:00Z to 2025-05-15T00:00Z
Fetching chunk: 2025-05-15T00:00Z to 2025-05-22T00:00Z
Fetching chunk: 2025-05-22T00:00Z to 2025-05-29T00:00Z
Fetching chunk: 2025-05-29T00:00Z to 2025-06-05T00:00Z
Fetching chunk: 2025-06-05T00:00Z to 2025-06-12T00:00Z
Fetching chunk: 2025-06-12T00:00Z to 2025-06-19T00:00Z
Fetching chunk: 2025-06-19T00:00Z to 2025-06-26T00:00Z
Fetching chunk: 2025-06-26T00:00Z to 2025-07-03T00:00Z
Fetching chunk: 2025-07-03T00:00Z to 2025-07-10T00:00Z
Fetching chunk: 2025-07-10T00:00Z to 2025-07-17T00:00Z
Fetching chunk: 2025-07-17T00:00Z to 2025-07-24T00:00Z
Fetching chunk: 2025-07-24T00:00Z to 2025-07-31T00:00Z
Fetching chunk: 2025-07-31T00:00Z to 2025-08-07T00:00Z
Fetching chunk: 2025-08-07T00:00Z to 2025-08-14T00:00Z
Fetching chunk: 2025-08-14T00:00Z to 2025-08-21T00:00Z
Fetching chunk: 2025-08-21T00:00Z to 2025-08-28T00:00Z
Fetching chunk: 2025-08-28T00:00Z to 2025-09-04T00:00Z
Fetching chunk: 2025-09-04T00:00Z to 2025-09-11T00:00Z
Fetching chunk: 2025-09-11T00:00Z to 2025-09-18T00:00Z
Fetching chunk: 2025-09-18T00:00Z to 2025-09-25T00:00Z
Fetching chunk: 2025-09-25T00:00Z to 2025-10-02T00:00Z
Fetching chunk: 2025-10-02T00:00Z to 2025-10-09T00:00Z
Fetching chunk: 2025-10-09T00:00Z to 2025-10-16T00:00Z
Fetching chunk: 2025-10-16T00:00Z to 2025-10-23T00:00Z
Fetching chunk: 2025-10-23T00:00Z to 2025-10-30T00:00Z
Fetching chunk: 2025-10-30T00:00Z to 2025-11-06T00:00Z
Fetching chunk: 2025-11-06T00:00Z to 2025-11-13T00:00Z
Fetching chunk: 2025-11-13T00:00Z to 2025-11-20T00:00Z
Fetching chunk: 2025-11-20T00:00Z to 2025-11-27T00:00Z
Fetching chunk: 2025-11-27T00:00Z to 2025-12-04T00:00Z
Fetching chunk: 2025-12-04T00:00Z to 2025-12-11T00:00Z
Fetching chunk: 2025-12-11T00:00Z to 2025-12-18T00:00Z
Fetching chunk: 2025-12-18T00:00Z to 2025-12-25T00:00Z
Fetching chunk: 2025-12-25T00:00Z to 2026-01-01T00:00Z
Fetching chunk: 2026-01-01T00:00Z to 2026-01-08T00:00Z
Fetching chunk: 2026-01-08T00:00Z to 2026-01-15T00:00Z
Fetching chunk: 2026-01-15T00:00Z to 2026-01-22T00:00Z
Fetching chunk: 2026-01-22T00:00Z to 2026-01-29T00:00Z
Fetching chunk: 2026-01-29T00:00Z to 2026-02-05T00:00Z
Fetching chunk: 2026-02-05T00:00Z to 2026-02-12T00:00Z
Fetching chunk: 2026-02-12T00:00Z to 2026-02-19T00:00Z
Fetching chunk: 2026-02-19T00:00Z to 2026-02-26T00:00Z
Fetching chunk: 2026-02-26T00:00Z to 2026-03-01T00:00Z

In [18]:

if not avail_raw.empty:
    
    avail_raw['publishTime'] = pd.to_datetime(avail_raw['publishTime'], utc=True)
    avail_raw['forecastDate'] = pd.to_datetime(avail_raw['forecastDate'], utc=True)
    
    delta = avail_raw['forecastDate'].dt.normalize() - avail_raw['publishTime'].dt.normalize()
    avail_raw['days_ahead'] = delta.dt.days
    
    avail_day_ahead = avail_raw[avail_raw['days_ahead'] == 2].copy()
    
    avail_clean = avail_day_ahead.groupby('forecastDate')['outputUsable'].sum().reset_index()
    avail_clean = avail_clean.rename(columns={'forecastDate': 'time', 'outputUsable': 'available_mw'})
    avail_clean.set_index('time', inplace=True)
    

else:
    print("Failed to fetch FOU2T14D.")
avail_clean

                           available_mw
time
2023-03-04 00:00:00+00:00       1212485
2023-03-05 00:00:00+00:00       1231482
2023-03-06 00:00:00+00:00       1408762
2023-03-07 00:00:00+00:00       1318548
2023-03-08 00:00:00+00:00       1271853
...                                 ...
2026-02-27 00:00:00+00:00       1449945
2026-02-28 00:00:00+00:00       1426063
2026-03-01 00:00:00+00:00       1598385
2026-03-02 00:00:00+00:00       1503345
2026-03-03 00:00:00+00:00         55012

[1094 rows x 1 columns]

In [19]:
import yfinance as yf
def get_commodities(days=30):
    """ Gas and Oil prices from Yahoo Finance."""
    gas = yf.Ticker("TTF=F").history(period=f"{days}d") # gas
    oil = yf.Ticker("BZ=F").history(period=f"{days}d") # Brent Crude
    return gas, oil

def fetch_commodities_month(start_str, end_str):
    print(f"Fetching Commodity Prices: {start_str} to {end_str}...")
    
    # TTF=F European Gas Benchmark, BZ=F  Brent Crude
    tickers = ["TTF=F", "BZ=F"]
    
    # yfinance's end date is exclusive
    yf_end = (end_date + timedelta(days=1)).strftime('%Y-%m-%d')
    
    df = yf.download(tickers, start=start_str, end=yf_end, progress=False)
    
    if 'Close' in df.columns:
        close_df = df['Close'].reset_index()
    # else:
    #     # Fallback for some yfinance version differences
    #     close_df = df.xs('Close', axis=1, level=0).reset_index() if isinstance(df.columns, pd.MultiIndex) else df.reset_index()
        
    close_df = close_df.rename(columns={"TTF=F": "gas_price", "BZ=F": "oil_price", "Date": "time"})
    
    # Timezone UTC datetime
    close_df['time'] = pd.to_datetime(close_df['time']).dt.tz_localize('UTC')
    return close_df
commodities_df = fetch_commodities_month(start_str, end_str)

Fetching Commodity Prices: 2023-03-02 to 2026-03-01...

C:\Users\steph\AppData\Local\Temp\ipykernel_32584\1158000229.py:17: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(tickers, start=start_str, end=yf_end, progress=False)

In [17]:
commodities_df

Ticker                      time   oil_price   gas_price
0      2022-03-02 00:00:00+00:00  112.930000  165.542999
1      2022-03-03 00:00:00+00:00  110.459999  160.822998
2      2022-03-04 00:00:00+00:00  118.110001  192.550003
3      2022-03-07 00:00:00+00:00  123.209999  227.201004
4      2022-03-08 00:00:00+00:00  127.980003  214.554001
...                          ...         ...         ...
1000   2026-02-23 00:00:00+00:00   71.489998   31.834000
1001   2026-02-24 00:00:00+00:00   70.769997   30.891001
1002   2026-02-25 00:00:00+00:00   70.849998   31.049999
1003   2026-02-26 00:00:00+00:00   70.750000   32.223999
1004   2026-02-27 00:00:00+00:00   72.480003   31.959000

[1005 rows x 3 columns]

In [18]:
monthly_mid_df

,dataset,startTime,dataProvider,settlementDate,settlementPeriod,price,volume
1,MID,2022-03-02 00:00:00+00:00,APXMIDP,2022-03-02,1,194.59,859.90
2,MID,2022-03-02 00:30:00+00:00,APXMIDP,2022-03-02,2,196.44,1208.55
4,MID,2022-03-02 01:00:00+00:00,APXMIDP,2022-03-02,3,171.47,949.40
6,MID,2022-03-02 01:30:00+00:00,APXMIDP,2022-03-02,4,182.31,1747.60
8,MID,2022-03-02 02:00:00+00:00,APXMIDP,2022-03-02,5,178.03,1073.55
...,...,...,...,...,...,...,...
140234,MID,2026-02-28 22:00:00+00:00,APXMIDP,2026-02-28,45,90.83,2331.40
140236,MID,2026-02-28 22:30:00+00:00,APXMIDP,2026-02-28,46,88.31,2552.95
140239,MID,2026-02-28 23:00:00+00:00,APXMIDP,2026-02-28,47,89.46,2607.10
140241,MID,2026-02-28 23:30:00+00:00,APXMIDP,2026-02-28,48,89.33,2137.65
140243,MID,2026-03-01 00:00:00+00:00,APXMIDP,2026-03-01,1,87.90,2244.90

In [19]:
monthly_mid_df.groupby('startTime').agg({'price': 'mean', 'volume': 'sum'}).reset_index()

                      startTime   price   volume
0     2022-03-02 00:00:00+00:00  194.59   859.90
1     2022-03-02 00:30:00+00:00  196.44  1208.55
2     2022-03-02 01:00:00+00:00  171.47   949.40
3     2022-03-02 01:30:00+00:00  182.31  1747.60
4     2022-03-02 02:00:00+00:00  178.03  1073.55
...                         ...     ...      ...
70063 2026-02-28 22:00:00+00:00   90.83  2331.40
70064 2026-02-28 22:30:00+00:00   88.31  2552.95
70065 2026-02-28 23:00:00+00:00   89.46  2607.10
70066 2026-02-28 23:30:00+00:00   89.33  2137.65
70067 2026-03-01 00:00:00+00:00   87.90  2244.90

[70068 rows x 3 columns]

In [ ]:

mid_clean = monthly_mid_df.rename(columns={'startTime': 'time'})
mid_clean['time'] = pd.to_datetime(mid_clean['time'], utc=True)
mid_clean.set_index('time', inplace=True)

mid_hourly = mid_clean.resample('1H').agg({'price': 'mean', 'volume': 'sum'})

C:\Users\steph\AppData\Local\Temp\ipykernel_33808\2872879525.py:8: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  mid_hourly = mid_clean.resample('1H').agg({'price': 'mean', 'volume': 'sum'})

In [ ]:
# avail_clean = availability_df.copy()
# avail_clean['time'] = pd.to_datetime(avail_clean['forecastDate'], utc=True)
# # If there are multiple zones reporting for the same day, sum them up
# avail_clean = avail_clean.groupby('time')['outputUsable'].sum().reset_index()
# avail_clean.set_index('time', inplace=True)

In [ ]:
comm_clean = commodities_df.copy()
comm_clean['time'] = pd.to_datetime(comm_clean['time'], utc=True)
comm_clean.set_index('time', inplace=True)

In [40]:
master_df = mid_hourly.join(comm_clean, how='left') \
                      .join(avail_clean, how='left')

In [44]:
cols_to_ffill = ['oil_price', 'gas_price', 'available_mw']
master_df[cols_to_ffill] = master_df[cols_to_ffill].ffill()

In [54]:
master_df['volume'] = master_df['volume'].replace(0.0, np.nan)

In [48]:
master_df.isna().sum()

price            2
volume           0
oil_price        0
gas_price        0
available_mw    48
dtype: int64

In [56]:
master_df[['price', 'volume']] = master_df[['price', 'volume']].interpolate(method='linear')

In [59]:
master_df.dropna(inplace=True)

In [61]:
master_df.to_csv('price_commo_avail_power_2023_2026.csv',index=True)